# Generated by Django 6.0.3 on 2026-03-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_userrole_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
    ]
