# Generated by Django 6.0.3 on 2026-03-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_manufacturer_remove_vehicle_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeequipment',
            name='assigned_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officeequipment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='officeequipment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officeequipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officeequipment',
            name='subsidiary',
            field=models.CharField(blank=True, choices=[('ITECO', 'ITECO'), ('Softworks', 'Softworks'), ('Telnet', 'Telnet'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='officeequipment',
            name='tag_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officeequipment',
            name='year_of_purchase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
