# Generated by Django 6.0.3 on 2026-03-27 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_emailrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.TimeField(default='09:00', help_text='Time of day to send expiry alert emails (HH:MM format)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable automatic email scheduling')),
                ('last_sent', models.DateTimeField(blank=True, editable=False, help_text='Last time emails were sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_email_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Schedule',
                'verbose_name_plural': 'Email Schedule',
            },
        ),
    ]
