# Generated by Django 6.0.3 on 2026-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_emailschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='alert_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days in advance to check for expiring items'),
        ),
    ]
