# Generated by Django 6.0.3 on 2026-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailschedule',
            name='alert_days',
            field=models.PositiveIntegerField(default=15, help_text='Number of days in advance to check for expiring items'),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='schedule_time',
            field=models.TimeField(default='10:00', help_text='Time of day to send expiry alert emails (HH:MM format)'),
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_certification', 'Pending Certification'), ('inactive', 'Inactive'), ('damaged', 'Damaged')], default='active', max_length=50),
        ),
    ]
