# Generated by Django 6.0.3 on 2026-04-09 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_emaildeliverylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_from', models.CharField(help_text='Name of the staff member who previously had this equipment', max_length=100)),
                ('transferred_from_department', models.CharField(blank=True, help_text='Department of the previous user', max_length=100, null=True)),
                ('transferred_from_email', models.EmailField(blank=True, help_text='Email of the previous user', max_length=254, null=True)),
                ('transferred_to', models.CharField(help_text='Name of the staff member receiving this equipment', max_length=100)),
                ('transferred_to_department', models.CharField(blank=True, help_text='Department of the new user', max_length=100, null=True)),
                ('transferred_to_email', models.EmailField(blank=True, help_text='Email of the new user', max_length=254, null=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for the transfer (e.g., "Staff reassignment", "Replacement")', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transfer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='vehicles.officeequipment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_transfers_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Transfer',
                'verbose_name_plural': 'Equipment Transfers',
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['-transfer_date'], name='vehicles_eq_transfe_c50e82_idx'), models.Index(fields=['equipment', '-transfer_date'], name='vehicles_eq_equipme_68ecda_idx')],
            },
        ),
    ]
