# Generated by Django 6.0.3 on 2026-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_officeequipment_regional_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeequipment',
            name='subsidiary',
            field=models.CharField(blank=True, choices=[('ITECO', 'ITECO'), ('Softworks', 'Softworks'), ('Telnet', 'Telnet'), ('Telnet Abuja', 'Telnet Abuja'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
