# Generated by Django 6.0.3 on 2026-04-20 15:02

from django.db import migrations, models


def normalize_telnet_abuja_subsidiary(apps, schema_editor):
    OfficeEquipment = apps.get_model('vehicles', 'OfficeEquipment')
    OfficeEquipment.objects.filter(subsidiary='Telnet Abuja').update(subsidiary='Telnet')


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_alter_officeequipment_subsidiary'),
    ]

    operations = [
        migrations.RunPython(normalize_telnet_abuja_subsidiary, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='officeequipment',
            name='subsidiary',
            field=models.CharField(blank=True, choices=[('ITECO', 'ITECO'), ('Softworks', 'Softworks'), ('Telnet', 'Telnet'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
