# Generated by Django 6.0.3 on 2026-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_alter_officeequipment_subsidiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
