# Generated by Django 6.0.3 on 2026-04-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_vehicle_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeequipment',
            name='equipment_type',
            field=models.CharField(choices=[('computer', 'Computer'), ('laptop', 'Laptop'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('copier', 'Copier'), ('ac', 'Air Conditioner'), ('generator', 'Generator'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
