# Generated by Django 6.0.3 on 2026-04-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_alter_officeequipment_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeequipment',
            name='equipment_type',
            field=models.CharField(choices=[('computer', 'Computer'), ('laptop', 'Laptop'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('copier', 'Copier'), ('ac', 'Air Conditioner'), ('generator', 'Generator'), ('furniture', 'Furniture'), ('phone', 'Phone/Communication'), ('appliance', 'Appliance'), ('safety', 'Safety Equipment'), ('network', 'Network Equipment'), ('electronics', 'Electronics'), ('office_supplies', 'Office Supplies'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
