# Generated by Django 6.0.3 on 2026-04-29 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_alter_officeequipment_equipment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name/title', max_length=200)),
                ('document_type', models.CharField(choices=[('license', 'Business License'), ('permit', 'Permit/Authorization'), ('certificate', 'Certificate'), ('insurance', 'Insurance Policy'), ('contract', 'Contract/Agreement'), ('registration', 'Registration Document'), ('compliance', 'Compliance Document'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the document', null=True)),
                ('issuing_authority', models.CharField(blank=True, help_text='Organization that issued the document', max_length=200, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Reference/license number', max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, help_text='Date the document was issued', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date the document expires', null=True)),
                ('renewal_date', models.DateField(blank=True, help_text='Date when renewal should be initiated', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('expiring_soon', 'Expiring Soon'), ('renewal_pending', 'Renewal Pending'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to deactivate this document')),
                ('document_file', models.FileField(blank=True, help_text='Upload the actual document file', null=True, upload_to='company_documents/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or renewal instructions', null=True)),
                ('responsible_person', models.CharField(blank=True, help_text='Person responsible for this document', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Document',
                'verbose_name_plural': 'Company Documents',
                'ordering': ['-expiry_date', 'name'],
                'indexes': [models.Index(fields=['expiry_date'], name='vehicles_co_expiry__7ddc43_idx'), models.Index(fields=['status'], name='vehicles_co_status_ac4d27_idx'), models.Index(fields=['document_type'], name='vehicles_co_documen_8a0982_idx')],
            },
        ),
    ]
