# Generated by Django 6.0.3 on 2026-04-30 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_companydocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydocument',
            options={'ordering': ['expiry_date'], 'verbose_name': 'Company Document', 'verbose_name_plural': 'Company Documents'},
        ),
        migrations.RemoveField(
            model_name='companydocument',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='companydocument',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='companydocument',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='companydocument',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='companydocument',
            name='document_number',
            field=models.CharField(blank=True, help_text='Document or certificate number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='location',
            field=models.CharField(blank=True, help_text='Where the document is stored', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='notify_days_before',
            field=models.PositiveIntegerField(default=30, help_text='Number of days before expiry to send notification'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='document_type',
            field=models.CharField(choices=[('business_license', 'Business License'), ('insurance', 'Insurance Certificate'), ('permit', 'Permit'), ('certification', 'Certification'), ('contract', 'Contract'), ('agreement', 'Agreement'), ('registration', 'Registration'), ('tax', 'Tax Certificate'), ('compliance', 'Compliance Document'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2027, 4, 30), help_text='When the document expires'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='issuing_authority',
            field=models.CharField(blank=True, help_text='Authority that issued the document', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='name',
            field=models.CharField(help_text='Document name or title', max_length=200),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='renewal_date',
            field=models.DateField(blank=True, help_text='Target date for renewal', null=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='responsible_person',
            field=models.CharField(blank=True, help_text='Person responsible for renewal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending_renewal', 'Pending Renewal'), ('renewed', 'Renewed')], default='active', max_length=50),
        ),
    ]
