# Generated by Django 6.0.3 on 2026-05-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_alter_companydocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeequipment',
            name='year_of_purchase',
        ),
    ]
