# Generated by Django 6.0.3 on 2026-05-15 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0024_remove_officeequipment_year_of_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Unique staff ID or employee number', max_length=50, unique=True)),
                ('first_name', models.CharField(help_text='Staff first name', max_length=100)),
                ('last_name', models.CharField(help_text='Staff last name', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Optional linked Django user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['staff_id', 'last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='companydocument',
            name='responsible_staff',
            field=models.ForeignKey(blank=True, help_text='Select an existing staff member responsible for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='vehicles.staffmember'),
        ),
        migrations.AddField(
            model_name='officeequipment',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Select an existing staff member for this equipment assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='vehicles.staffmember'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['staff_id'], name='vehicles_st_staff_i_56da04_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['last_name', 'first_name'], name='vehicles_st_last_na_e362a9_idx'),
        ),
    ]
