# Generated by Django 6.0.3 on 2026-05-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0025_staffmember_companydocument_responsible_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='related_equipment',
            field=models.ForeignKey(blank=True, help_text='Optional equipment this document applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_documents', to='vehicles.officeequipment'),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='related_vehicle',
            field=models.ForeignKey(blank=True, help_text='Optional vehicle this document applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_documents', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Select an existing staff member assigned to this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.staffmember'),
        ),
    ]
