# Generated by Django 6.0.3 on 2026-05-19 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0026_companydocument_related_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Asset display name', max_length=200)),
                ('asset_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_certification', 'Pending Certification'), ('inactive', 'Inactive'), ('damaged', 'Damaged')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, help_text='Staff assigned to this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='vehicles.staffmember')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='companydocument',
            name='related_asset',
            field=models.ForeignKey(blank=True, help_text='Optional shared asset that this document applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_documents', to='vehicles.asset'),
        ),
        migrations.AddField(
            model_name='officeequipment',
            name='asset',
            field=models.OneToOneField(blank=True, help_text='Linked asset record for this equipment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='vehicles.asset'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='asset',
            field=models.OneToOneField(blank=True, help_text='Linked asset record for this vehicle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicles.asset'),
        ),
    ]
