# Generated by Django 6.0.3 on 2026-05-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0027_asset_companydocument_related_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, help_text='Branch where the asset is assigned', max_length=100, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('related', 'Related'), ('attached_to', 'Attached To'), ('supports', 'Supports'), ('document_for', 'Document For'), ('sub_asset', 'Sub Asset')], default='related', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='staffmember',
            name='branch',
            field=models.CharField(blank=True, help_text='Primary Telnet branch', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['branch'], name='vehicles_st_branch_308c2e_idx'),
        ),
        migrations.AddField(
            model_name='assetassignmenthistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.asset'),
        ),
        migrations.AddField(
            model_name='assetassignmenthistory',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetassignmenthistory',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='vehicles.staffmember'),
        ),
        migrations.AddField(
            model_name='assetrelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetrelationship',
            name='from_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_asset_relationships', to='vehicles.asset'),
        ),
        migrations.AddField(
            model_name='assetrelationship',
            name='to_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_asset_relationships', to='vehicles.asset'),
        ),
        migrations.AddIndex(
            model_name='assetassignmenthistory',
            index=models.Index(fields=['asset'], name='vehicles_as_asset_i_8a4c45_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignmenthistory',
            index=models.Index(fields=['staff_member'], name='vehicles_as_staff_m_937d43_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignmenthistory',
            index=models.Index(fields=['assigned_at'], name='vehicles_as_assigne_6c7a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrelationship',
            index=models.Index(fields=['relation_type'], name='vehicles_as_relatio_254303_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrelationship',
            index=models.Index(fields=['created_at'], name='vehicles_as_created_1203f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetrelationship',
            unique_together={('from_asset', 'to_asset', 'relation_type')},
        ),
    ]
