# Generated by Django 6.0.3 on 2026-05-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0028_assetassignmenthistory_assetrelationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='branch',
            field=models.CharField(blank=True, choices=[('LAGOS', 'LAGOS'), ('ABUJA', 'ABUJA'), ('PORT_HARCOURT', 'Port Harcourt')], help_text='Primary Telnet branch', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='department',
            field=models.CharField(blank=True, choices=[('ABS', 'ABS'), ('ITECO', 'ITECO'), ('SOFTWORKS', 'SOFTWORKS'), ('HR', 'HR'), ('MANAGEMENT', 'MANAGEMENT')], help_text='Staff department within Telnet', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Asset', max_length=100)),
                ('license_plate', models.CharField(blank=True, default='UNKNOWN', help_text='License plate for vehicles', max_length=20, null=True, unique=True)),
                ('asset_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('motorbike', 'Motorbike')], default='car', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_certification', 'Pending Certification'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('roadworthy_expiry', models.DateField(blank=True, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('hackney_permit', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(blank=True, help_text='Linked asset record for this asset', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_asset', to='vehicles.asset')),
                ('assigned_staff', models.ForeignKey(blank=True, help_text='Select an existing staff member assigned to this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_assets', to='vehicles.staffmember')),
            ],
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='related_vehicle',
            field=models.ForeignKey(blank=True, help_text='Optional company asset this document applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_documents', to='vehicles.companyasset'),
        ),
        migrations.AlterField(
            model_name='maintenanceitem',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_items', to='vehicles.companyasset'),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
