# Generated by Django 6.0.3 on 2026-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0029_alter_staffmember_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyasset',
            name='make',
            field=models.CharField(blank=True, help_text='Vehicle make or brand', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='model',
            field=models.CharField(blank=True, help_text='Vehicle model', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='vin_number',
            field=models.CharField(blank=True, help_text='Vehicle VIN number', max_length=100, null=True, unique=True),
        ),
    ]
