# Generated by Django 6.0.3 on 2026-07-14 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0030_companyasset_make_companyasset_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='driver_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('on_leave', 'On Leave')], default='available', help_text='Driver availability status for assignment workflows', max_length=20),
        ),
        migrations.CreateModel(
            name='DriverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Manager or admin who assigned the driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_driver', models.ForeignKey(blank=True, help_text='Driver assigned to handle this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver_requests', to='vehicles.staffmember')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Staff member who created the driver request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_requests', to='vehicles.staffmember')),
                ('requester_user', models.ForeignKey(blank=True, help_text='User who created the driver request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Request',
                'verbose_name_plural': 'Driver Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='vehicles_dr_status_7ba4e5_idx'), models.Index(fields=['requested_by'], name='vehicles_dr_request_dc5cb9_idx'), models.Index(fields=['assigned_driver'], name='vehicles_dr_assigne_025df0_idx')],
            },
        ),
    ]
