# Generated by Django 6.0.3 on 2026-07-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0031_staffmember_driver_status_driverrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehicles.companyasset',),
        ),
    ]
