# Generated by Django 6.0.3 on 2026-08-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0032_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='document_file',
            field=models.FileField(blank=True, help_text='Optional uploaded document file', null=True, upload_to='company_documents/'),
        ),
    ]
