# Generated by Django 6.0.3 on 2026-09-28 17:28

import django.db.models.deletion
from django.db import migrations, models


def seed_existing_equipment_work_orders(apps, schema_editor):
    OfficeEquipment = apps.get_model('vehicles', 'OfficeEquipment')
    EquipmentWorkOrder = apps.get_model('vehicles', 'EquipmentWorkOrder')
    status_config = {
        'damaged': ('repair', 'Repair required', 'high'),
        'pending_certification': ('certification', 'Certification required', 'medium'),
    }

    for equipment in OfficeEquipment.objects.filter(status__in=status_config).iterator():
        work_type, title, priority = status_config[equipment.status]
        EquipmentWorkOrder.objects.create(
            equipment_id=equipment.pk,
            work_type=work_type,
            title=f'{title}: {equipment.name}',
            description=f'Automatically created for existing equipment with status {equipment.status}.',
            priority=priority,
            status='open',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0033_companydocument_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('repair', 'Repair'), ('certification', 'Certification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='vehicles.officeequipment')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'in_progress'])), fields=('equipment', 'work_type'), name='unique_active_equipment_work_order')],
            },
        ),
        migrations.RunPython(seed_existing_equipment_work_orders, migrations.RunPython.noop),
    ]
