# Generated by Django 6.0.3 on 2026-10-08 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0034_equipment_work_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('staff_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('ABS', 'ABS'), ('ITECO', 'ITECO'), ('SOFTWORKS', 'SOFTWORKS'), ('HR', 'HR'), ('MANAGEMENT', 'MANAGEMENT')], max_length=50)),
                ('branch', models.CharField(choices=[('LAGOS', 'LAGOS'), ('ABUJA', 'ABUJA'), ('PORT_HARCOURT', 'Port Harcourt')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_application', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staff_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='vehicles_st_status_6a455c_idx')],
            },
        ),
    ]
